### ISSUE TITLE
Need help with code

### ISSUE THREAD

**Issue by Julian123451** [dudaster/ele-conditions#1]
Hi!

I don't understand how to write the condition properly. I need a section to only show on front page.

**Comment by dudaster** [comment]
Hi unfortunatly is not that user friendly but if you know how to code a little you can write in function.php this code:

```

add_filter( "eleconditions_vars",function($custom_vars){
$custom_vars["is_front_page"]=is_front_page();
return $custom_vars;
});


```
and in the condition textarea add:

`is_front_page === true`

**Comment by Julian123451** [comment]
It didn't work.. I just put it on the bottom of my themes functions.php. Was that correct?

**Comment by dudaster** [comment]
@Julian123451 try to see if it works on a widget, first. I tested the code myself and it is working for me.
Let me know if it works.

**Comment by dudaster** [comment]
If it works try to save the section as a template and add it to your page as a template widget with the same condition.

**Comment by Julian123451** [comment]
I'm trying to use the code on Elementor's Header Footer plugin. Will it work with this plugin?

**Comment by dudaster** [comment]
It should. If not, we have an alternative, check out: https://www.eletemplator.com/
