### ISSUE TITLE
How to Hide / Reveal Content or Button

### ISSUE THREAD

**Issue by dmorizz** [dudaster/ele-conditions#10]
How do I hide an Elementor Button (Section or Column) for a specific amount of time, then reveal.

E.g. On Demand video > Hide ‘Buy Now’ button for 1 hr 3 min 25 sec > Then reveal button and keep visible.

**Comment by dudaster** [comment]
https://www.eletemplator.com/ele-conditions/ check this page and you'll have all the info you need.

**Comment by dmorizz** [comment]
I have been looking at your examples and experimenting with different options, but haven't been able to get it to work. 

I don't know what vars to use and how to write/structure it properly so it works, as I want this to be evergreen for each visitor.

I'm not a coder (I'm a self-taught dabbler :) , so I struggle in this area. Any help would be much appreciated.

**Comment by dudaster** [comment]
Sorry currently I don't have time to go to the bathroom :), please ask a fellow coder i'm sure he'll help you.
