### ISSUE TITLE
Target multiple fields

### ISSUE THREAD

**Issue by ianandersonmedia** [dudaster/ele-conditions#12]
Hi,
Is it possible to hide a section if 2 specific custom fields are null?
For example a condition like $program_email & $program_website != null
Thanks!
Ian

**Comment by dudaster** [comment]
I'm afraid you need to write a little code in function for it to work:
```
add_filter( "eleconditions_vars",function($custom_vars){
	if (get_field('program_email') && get_field('program_website')) $custom_vars['isvalid']=true;
		$custom_vars['isvalid']=true;
	}
	return $custom_vars;
});
```
and the condition could look like this:
`$isvalid == true `

Hope this would help you/
