### ISSUE TITLE
Please update the repo

### ISSUE THREAD

**Issue by ramiy** [dudaster/ele-conditions#13]
Seems like the GitHub repo hosts version 1.0.0 while the [Plugin Directory](https://wordpress.org/plugins/ele-conditions/) hosts version 1.0.5.

Can you update this repo.

BTW, I [translated the plugin](https://translate.wordpress.org/projects/wp-plugins/ele-conditions/) to Hebrew.

**Comment by dudaster** [comment]
Haven't had time... but I will. Thanks for pointing it out!
