### ISSUE TITLE
Using Ele Conditions and Ele Custom Skin Pro together

### ISSUE THREAD

**Issue by bryanb** [dudaster/ele-conditions#16]
Hello.  
I love the plugins, they've been great so far.  But my success so far has pushed me to look to do more.  

I've created a skin for a loop.  I use {{index}} and Custom Skin Pro to display the current number of the item in the list.  This works great.  
Is there a simple way to use Ele Conditions and {{index}} in a condition for deciding to display an element?  From the results I've seen it seems like the condition is evaluated before the {{index}} is substituted.  

If not, any suggestions/hints on how to do this in code?  I've tried a few different ways but none have worked yet.  I thought trying to get the found_posts amount might work, but I haven't been successful.

Thanks!

**Comment by dudaster** [comment]
Let me know if this helps you: https://github.com/dudaster/ele-custom-skin/issues/66

**Comment by bryanb** [comment]
Hi.  That works well!  Thanks.
Is there a list of global variables the plugins use available somewhere? I, of course, ask that first before looking through the code so it might be obvious, but it might be handy to have it to spark more ideas of what can be done with your work.
Thanks again.

**Comment by dudaster** [comment]
You can check out this page https://dudaster.com/dynamic-everywhere/ for the default values.
Basically all you can find in a wp_query.
