### ISSUE TITLE
Checking for empty post content

### ISSUE THREAD

**Issue by riderworks** [dudaster/ele-conditions#18]
Hi, I have an Elementor button that I want to hide whenever the Post Content field is empty. How would I do that? 
Thanks.
Doug

**Comment by dudaster** [comment]
Use Ele Condition plugin, more info here: https://www.eletemplator.com/ele-conditions/

**Comment by riderworks** [comment]
I am using it. I can't get it to work. I added this in the plugin.

// Add Check for Post content
add_filter( 'eleconditions_vars', 'elecond_post_content');
function elecond_post_content( $custom_vars ) {
    $custom_vars['pcontent']=the_content();
    return $custom_vars;
}

Then added the following to the Elementor Button Widget Condition field. I want to hide the Button when "the_content" is empty.

$pcontent == null

I've tried all permutations of that, but I still can't get it to work.

**Comment by dudaster** [comment]
Turn on debut mode and make a screenshot

**Comment by riderworks** [comment]
Hi, here’s the code is using:

add_filter( 'eleconditions_vars', function($custom_vars) {
$custom_vars['pcontent']=the_content();
return $custom_vars;
});
$pcontent=null

Here’s the snapshot of the debug.



I’m trying to HIDE the button when there is no content in the post. There will always be Title, Featured Image, Date, and Excerpt.
--
Doug Rider

**Comment by dudaster** [comment]
it works only with == not = .
Please try again to attach the screenshot.

**Comment by riderworks** [comment]
Still the same issue. I tried it with an Elementor button. Previously used the AE button.

Is the WordPress content field “the_content”??





--
Doug Rider

**Comment by dudaster** [comment]
Try this code:

```
add_filter( 'eleconditions_vars', function($custom_vars) {
   $custom_vars['pcontent']=trim(get_the_content()) ? true : false;
   return $custom_vars;
});
```

and for condition

`pcontent == true`

Let me know if it works.

Thanks!

**Comment by riderworks** [comment]
Hi, it just removes the button entirely for all posts when the Debug mode is unchecked





--
Doug Rider

**Comment by dudaster** [comment]
Debug mode needs to be checked too se why is not working. Please provide me a screenshot of the debug mode to see what is the problem.

**Comment by riderworks** [comment]
Here’s the debug on the post archives.

Just to be clear: on the archive page I want the “Read more” button to display only when there is some data in the WP Content field. If the WP Content field is empty, then don’t display the “Read more” button.

This Archive is built using the AnyWhere Elementor Pro plugin.


--
Doug Rider

**Comment by dudaster** [comment]
Please go to GitHub and reply to this message and see that you didn’t send any screenshot so far!

**Comment by riderworks** [comment]
<img width="1000" alt="Screenshot of Safari (12-13-19, 11-16-04 PM)" src="https://user-images.githubusercontent.com/1690435/70845047-e4751b00-1dfe-11ea-843d-769a6f71be19.png">

**Comment by dudaster** [comment]
The code I sent you needs to be add in you child themes function.php

**Comment by riderworks** [comment]
Great. That worked. Thanks so much.
--
Doug Rider
