### ISSUE TITLE
Use OR and AND

### ISSUE THREAD

**Issue by gianghl1983** [dudaster/ele-conditions#2]
Can we use OR / AND in condition like this 1 < $hour <10?

Many thanks for this great plugin!

**Comment by dudaster** [comment]
Currently not. But you can create your own custom value and add in condition something like:

$custom_value === true

Please see an example how to do it using add filter here: https://www.eletemplator.com/ele-conditions/

**Comment by gianghl1983** [comment]
I see, thank you!
