### ISSUE TITLE
This plugin hasn’t been tested with the latest 3 major releases of WordPress.

### ISSUE THREAD

**Issue by itseoconsulting** [dudaster/ele-conditions#24]
Hi, the plugin and how it's works is pretty clear.

Only 1 question left: Are you still have an eye on the plugin and test it regular?

I ask since I read at  wordpress.org: This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

https://wordpress.org/plugins/ele-conditions/

Please advise. Thank you!

**Comment by dudaster** [comment]
Yes I Keep an eye on it.

**Comment by itseoconsulting** [comment]
Hi & thanks for feedback,

Maybe just update the WP repo details and mark it as compatible with the current version of Elementor and WordPress IMO :)

Thx
