### ISSUE TITLE
Cache Plugin compatible!

### ISSUE THREAD

**Issue by gianghl1983** [dudaster/ele-conditions#3]
Is there anyway this plugin work with cache plugin? I tried but not succces!

**Comment by dudaster** [comment]
haven't had any issues with litespeed cache or WP Fastest Cache

**Comment by gianghl1983** [comment]
I tried it 1 time like this (Custom PHP)

Check current time = 8:00 - 17:00 then display block A, if time > 17:00 display B

It always display A regarless what time it is after caching with Cache Enabler...

**Comment by dudaster** [comment]
Does it change eventually?

**Comment by gianghl1983** [comment]
I will try again (long time no use Ele Condition due to that problem) and give you feedback!
