### ISSUE TITLE
need help with code please

### ISSUE THREAD

**Issue by emailjough** [dudaster/ele-conditions#4]
hi, i am trying to do something simple for people who know php but i am a beginner. please help!

I am attempting to only display social media links on a board member bio if there is a value in the field. i.e. if they have a twitter url then display the twitter icon w/link, otherwise, hide it. 
same with facebook, linkedin, instagram etc. 

i have an ACF field called 'board_twitter' and my template currently displays the icon whether there is a link or not. 

in functions.php I've tried this but doesnt work:

/* assign ACF field to variable */
add_filter( "eleconditions_vars", function($twitter){
	$twitter = get_field('board_twitter');
	return $twitter;
});

and in my condition box for the element i tried this but doesnt work:

$twitter !== ""

Obviously not right, but I am not sure how to make work.

**Comment by dudaster** [comment]
click on debug switch and you'll see how the code is proper wrote and what values vars have.

All ACF fields by default are loaded so I don't think you need to add a code, make sure the value is ok.

Try: $board_twitter !== false

**Comment by emailjough** [comment]
Thank you for fast reply. I removed my code from functions.php, adjusted my
condition per your suggestion (and tried variations) and turned on debug.
Condition seems to be evaluating to true even when the field is blank.

Here I tried simply  $board_twitter == true    assuming that if there is a
link present in the ACF field then it would evaluate to true, and if no
link then it would evaluate to false. However, the icon element appears on
the page whether there is a link or not.

It is the icon element I want to hide based on whether or not a link has
been entered in the ACF field.

Do you see what I am doing wrong?

[image: Screen Shot 2018-11-17 at 7.23.34 AM.png]

**Comment by mass43** [comment]
Same issue for me (with Pods).
If I use :  $video == false

The debug gives me this on a page where the value $video is empty : 
```
$video == false
video == false -> false
```

On a page with $video not empty : 
```
$video == false
https://www.youtube.com/watch?v=znLH1HG0iy4 == false -> false
```

**Comment by dudaster** [comment]
I see the problem now. I know it is counter intuitive but you can add the conditions like this:

$board_twitter != board_twitter
$video != video

and it will work.

**Comment by mass43** [comment]
Thank you for the feedback, unfortunately it does not work. I gives me this : 

```
$video != video
video != video -> false
```
and this 
```
$video != video
https://www.youtube.com/watch?v=9yfUiBvw-BY != https://www.youtube.com/watch?v=9yfUiBvw-BY -> false
```

**Comment by dudaster** [comment]
Working on a fix.

**Comment by emailjough** [comment]
thanks for working on a fix. will be super helpful once this gets working.

for fun i also tried your suggestion: $board_twitter != board_twitter  and it returns false even when i know its true.

**Comment by dudaster** [comment]
Please but you can add the conditions like this:

$board_twitter != null
$video != null

and it will work.

**Comment by emailjough** [comment]
I tried this and retried and it does not work

$board_twitter != null

it evaluates to true even when it is false

In the following example, the board member has an instagram URL but does not have a twitter URL:
$board_instagram != null
board_instagram != null -> true
$board_instagram != null
board_instagram != null -> true

$board_twitter != null
board_twitter != null -> true
$board_twitter != null
board_twitter != null -> true

So on front end  both icons always show but only one is hyperlinked.

Also tried

$board_twitter != ""
$board_twitter != false
$board_twitter = true

**Comment by mass43** [comment]
For me too, same issue, I did tried every combinaison too

**Comment by dudaster** [comment]
My bad guys! I need to push the update first. Hold on!

**Comment by dudaster** [comment]
I hope it will work. The new version is up. Didn't had time to do to much testing. Let me know if it works ok.

**Comment by mass43** [comment]
It works thank you so much !!!!

**Comment by emailjough** [comment]
Latest release works for me. Thank you for fixing

**Comment by dudaster** [comment]
In the latest version you can also do something like:

$board_twitter == true
$video == true

**Comment by dudaster** [comment]
And don't forget you can add complex conditions also using this code in your functions.php:
```
add_filter( “eleconditions_vars”,function($custom_vars){
  global $product;
  if ( isset( $product ) ) {
          if ( ! $product->managing_stock() && ! $product->is_in_stock() ) $custom_vars[‘instock’]=false;
          else
          $custom_vars[‘instock’]=true;
     }
     return $custom_vars;
});
```

and use in condition:

$instock == true

**Comment by dudaster** [comment]
you can also add multiple values of course:

```
add_filter( "eleconditions_vars",function($custom_vars){
   $custom_vars["myvar"]=true;
   $custom_vars["myval"]=6;
   $custom_vars["fixedval"]='something';
   $custom_vars["current_year"]=date("Y");  
   return $custom_vars;
});
```
