### ISSUE TITLE
New release broke all conditions

### ISSUE THREAD

**Issue by shaneonabike** [dudaster/ele-conditions#5]
Your latest release with reference to issue #4 seems to have broken all my conditions. I had to revert to an old version, and would ask that you tag your revisions so it's easier for folks to download older versions.

Basically, I was using $my_variable !== false and I noticed that now your code is stripped out the ! so it never actually works. Actually, I don't think it is parsing the string properly but you can test it out and see what I mean.

Thanks for making a rad plugin this really saved my life

**Comment by dudaster** [comment]
Sorry about that! I’ll fixit ASAP. Can you please go to debug mode and copy paste what it said?

**Comment by dudaster** [comment]
Hi @shaneonabike, a new update is up. Can you check if the problem is solved with the new version?
Thanks!

**Comment by shaneonabike** [comment]
Yep it seems happy as a clam thanks
