### ISSUE TITLE
Something not quite right

### ISSUE THREAD

**Issue by brent-e** [dudaster/ele-conditions#7]
Hi, I'm using Elementor Pro 2.2.4 and Toolset with the Astra theme. I have a Toolset custom field 'email' that I want to display only if there's is a value for it. I set  this condition on an instance of The Icon Box widget: 

$email != null

The first post I checked looked fine -- 'email' had no value and so the widget didn't display. But the next post _did_ have a value for 'email' but the widget still didn't display.

I'm not sure what I'm missing here.

![image](https://user-images.githubusercontent.com/45741358/49702682-e5121a80-fbc8-11e8-8043-d4d1fc4e6282.png)

**Comment by dudaster** [comment]
Please use debug mode to see what’s going on there!

**Comment by brent-e** [comment]
Thanks for the quick reply. I forgot to mention that I'd put debug on and it showed the condition as 'false'. But I was just testing more and accidentally typed the var name as **$rmail** and it still returned the same result. So now I'm confused :)

![image](https://user-images.githubusercontent.com/45741358/49764782-6e475100-fc9e-11e8-8359-948889202cc6.png)

**Comment by dudaster** [comment]
I don’t see the confusion here, $rmail is a miss typed,  it doesn’t exist, so it means it is null.  $rmail != null -> false
