### ISSUE TITLE
Support for url parameter values

### ISSUE THREAD

**Issue by lazmo88** [dudaster/ele-conditions#8]
Hello, any plans building a support for url parameters or is there an existing workaround? Latest Elementor Pro supports url parameters out of the box, would be cool to use url params for conditional logic as well.

**Comment by dudaster** [comment]
You can with add filter. Go to eletemplator.com for more details!

**Comment by lazmo88** [comment]
Thanks, you are referring to this?

**Comment by lazmo88** [comment]
Thanks, are you referring to this part of the FAQ?

By default you can’t add more than one simple condition but you can add your own variabile like this:
/*adding custom values to conditions*/

add_filter( "eleconditions_vars",function($custom_vars){
	global $product;
	if ( isset( $product ) ) {
		if ( ! $product->managing_stock() && ! $product->is_in_stock() ) $custom_vars['instock']=false;
	else
		$custom_vars['instock']=true;
	}
	return $custom_vars;
});
and in condition to the add to cart element you enter:
$instock == true
In this way the add to cart button will show only if the product is in stock. Also you can use it in loop.

While scripting this is a viable option, I would assume many Elementor Pro users would like to see full support on natively offered features ;)

**Comment by dudaster** [comment]
Yes you can use add_filter() to add whatever you want in conditions.

I think there are other plugins that have easy administrative conditioning features. This one was made dev oriented for complex conditions. Probably in the future if I have time I’ll build a complex GUI, but for now it works as intended.
