### ISSUE TITLE
Archive Posts to show one category

### ISSUE THREAD

**Issue by wilsondesigned** [dudaster/ele-conditions#9]
Hello -

I am designing a search results archive template in Elementor and want to use this plugin on my Archive Posts widget to display only the posts in the "tutorial" category. I can't seem to figure out the right code to do this if it is possible. What's the best way or the best code to plug that into the conditions code box? 

Thanks

**Comment by dudaster** [comment]
I'm afraid is not posibile... you need to alter the wp_query for this job.
